### ISSUE TITLE
Footer typo in string -> Donwload instead of Download

### ISSUE THREAD

**Issue by amirmuminovic** [cesswhite/hato-minimal-template#1]
In the footer for the template, there is a typo in the word `Download` - it's written as `Donwload`:
<img width="1193" alt="image" src="https://github.com/cesswhite/hato-minimal-template/assets/37328370/6fe2c412-4a89-4dcb-86d5-c314e720094f">

**Comment by cesswhite** [comment]
Fix it, thank you
